# Generated by Django 3.2.19 on 2023-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.TextField(default='na', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.TextField(default='na', max_length=100),
        ),
        migrations.AddField(
            model_name='newfeature',
            name='details',
            field=models.TextField(default='na', max_length=500),
        ),
        migrations.AddField(
            model_name='newfeature',
            name='name',
            field=models.TextField(default='na', max_length=100),
        ),
    ]
